name: sleepaid
description: Sleep Aid
publish_to: 'neurotx'

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

#  package_info_plus: ^1.4.2
  cupertino_icons: ^1.0.2
  flutter_phoenix: ^1.0.0
  permission_handler: ^9.0.1
  provider: ^6.0.2
  #  flutter_reactive_ble: ^5.0.2 # 완전 새로 짜도 된다고 하면 이걸 쓰는게 나을 것 같은데 좀 더 체크 필요
  #  flutter_ble_lib: ^2.3.2 # 기존 프로젝트에서 사용되던 패키지, but 업데이트 1년 반 전에 종료되어서 신규 IOS, ANDROID 미지원 상태(앞으로도 문제될듯)
#  flutter_ble_lib_ios_15: ^2.5.2 # 일단 IOS 15는 지원하는 버전(안드로이드 12 미지원)
  flutter_reactive_ble: ^5.0.2 # 안드로이드 12 지원

  intl: ^0.17.0
  logger: ^1.1.0
  animations: ^2.0.2
  sembast: 3.1.0+2
  path_provider: 2.0.4
  http: ^0.13.4
  fluttertoast: 8.0.4
#  package_info_plus: 1.2.0
  package_info_plus: ^1.4.2
  another_xlider: 1.0.0
#  syncfusion_officechart: ^20.1.60-beta
  surround_sound: ^0.3.2
  calendar_appbar: ^0.0.6
  internet_connection_checker: 0.0.1+3
#  syncfusion_flutter_charts: 19.4.52 #차트(그래프) 라이브러리 기존 앱에서 쓰는 차트 ///todo 문의 후 삭제해야 할수도 있음
  flutter_naver_login: 1.6.0
  google_sign_in: ^5.4.1
  flutter_login_facebook: ^1.5.0+1

  #  flutter_naver_login: 1.2.4
  headset_connection_event: ^2.1.1
  app_settings: ^4.1.8
  android_intent_plus: ^3.1.1

  firebase_core: ^1.20.0
  firebase_auth: ^3.6.2
  firebase_messaging: ^12.0.1
  flutter_local_notifications: ^9.7.0
  syncfusion_flutter_charts: ^20.3.50


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_launcher_icons: "^0.9.2"


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/background_images/