// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFDeW4erT-KBCQSnAeV-z6gYvjXdycxys',
    appId: '1:492902760774:android:90756f26996bc95b4fe547',
    messagingSenderId: '492902760774',
    projectId: 'sleepaid-1eae8',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFDeW4erT-KBCQSnAeV-z6gYvjXdycxys',
    appId: '1:492902760774:ios:6dd8d853f66fec204fe547',
    messagingSenderId: '492902760774',
    projectId: 'sleepaid-1eae8',

    // androidClientId:
    // '406099696497-tvtvuiqogct1gs1s6lh114jeps7hpjm5.apps.googleusercontent.com',
    // iosClientId:
    // '406099696497-taeapvle10rf355ljcvq5dt134mkghmp.apps.googleusercontent.com',
    // iosBundleId: 'io.flutter.plugins.firebase.tests',
  );
}
